version: 2.1

jobs:
  build:
    docker:
       - image: circleci/node
    working_directory: ~/circleci-demo-schdeule   
    steps:
      - checkout
      - run:  
            name: Run build Command
            command: echo "build command Running"

  deploy:
    docker:
       - image: circleci/node
    working_directory: ~/circleci-demo-schdeule   
    steps:
      - checkout
      - run:  
            name: Run build Command
            command: echo "deploy command Running"        

workflows:
  version: 2
  commit-workflows:
    jobs:
     - build
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
              - master
    jobs:
      - build
      - deploy